# Generated by Django 4.2.30 on 2026-10-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_alter_question_question_type_auditevent_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='delivery_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='delivery_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='participant',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
