# Generated by Django 4.2.30 on 2026-10-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_participant_delivery_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='response_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('survey', 'response_id'), name='unique_survey_response_id'),
        ),
    ]
